# Databricks App Configuration
# Arquivo de configuração para startup e environment variables

command:
  - "sh"
  - "-c"
  - "cd backend && ../.venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port 8000"

env:
  - name: DATABRICKS_HOST
    value: "adb-116288240407984.4.azuredatabricks.net"

  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "sql-warehouse"

  - name: FRONTEND_URL
    value: "{{app.url}}"

  - name: CATALOG
    value: "hs_franquia"

  - name: SCHEMA_GOLD
    value: "gold_connect_bot"
